name: Context

on: push

env:
  EXAMPLE: workflow level

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      EXAMPLE: job level
    steps:
      - run: echo "-----------------------------------------------"
      - run: echo "githubコンテキスト"
      - run: echo "-----------------------------------------------"
      - run: echo "github.actor = ${{ github.actor }}"
      - run: echo "github.run_id = ${{ github.run_id }}"
      - run: echo "github.head_ref = ${{ github.head_ref }}"
      - run: echo "github.workspace = ${{ github.workspace }}"
      - run: echo "github.repository = ${{ github.repository }}"
      - run: echo "github.repository_owner = ${{ github.repository_owner }}"
      - run: echo "github.path = ${{ github.path }}"
      - run: echo "github.event = ${{ github.event }}" # eventは唯一のオブジェクト型

      - run: echo "-----------------------------------------------"
      - run: echo "runnerコンテキスト"
      - run: echo "-----------------------------------------------"
      - run: echo "runner.name = ${{ runner.name }}"
      - run: echo "runner.os = ${{ runner.os }}"
      - run: echo "runner.arch = ${{ runner.arch }}"
      - run: echo "runner.name = ${{ runner.name }}"
      - run: echo "runner.temp = ${{ runner.temp }}"
      - run: echo "runner.tool_cache = ${{ runner.tool_cache }}"
      - run: echo "runner.debug = ${{ runner.debug }}"

      - run: echo "-----------------------------------------------"
      - run: echo "env"
      - run: echo "-----------------------------------------------"
      - run: echo "env.BRANCH = ${{ env.BRANCH }}"
      - run: echo "env.EXAMPLE = ${{env.EXAMPLE}}"
      - env:
          EXAMPLE: step level
        run: echo "env.EXAMPLE = ${{ env.EXAMPLE }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - run: echo "$CI" # 単純に値がなかっただけっぽい
      - run: echo "${CI}" # 単純に値がなかっただけっぽい
      - run: echo "${{ env.CI }}" # 単純に値がなかっただけっぽい

      - run: |
          echo "SHA:        $GITHUB_SHA"
          echo "Ref:        $GITHUB_REF"
          echo "Run ID:     $GITHUB_RUN_ID"
          echo "Runner OS:  $RUNNER_OS"

      - run: echo "-----------------------------------------------"
      - run: echo "variables"
      - run: echo "-----------------------------------------------"
      - run: echo "USERNAME is ${USERNAME}"
        env:
          USERNAME: ${{ vars.USERNAME }}

      - run: echo "USERID is $USERID"
        env:
          USERID: ${{ vars.USERID }}
      - run: echo "-----------------------------------------------"
      - run: echo "secrets"
      - run: echo "-----------------------------------------------"
      - run: |
          echo "PASSWORD is $PASSWORD" # PASSWORD is ***
          echo "${PASSWORD:0:1} ${PASSWORD#?}" # s uperSecret!!
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - run: echo "-----------------------------------------------"
      - run: echo "式"
      - run: echo "-----------------------------------------------"
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 1234 }}
          LITERAL_STRING: ${{ 'HELLO' }}
          LITERAL_OMIT_STRING: World
      # - run: echo "object filtering ${github.event.*.html_url}"

      - run: echo "-----------------------------------------------"
      - run: echo "関数"
      - run: echo "-----------------------------------------------"
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTSWITH_FUNC: ${{ startsWith('Hello', 'Hel') }}
          ENDSWITH_FUNC: ${{ endsWith('Hello', 'llo') }}
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hello', 'World') }}
          JOIN_FUNC: ${{ join('Hello, World!!', ',') }}
          TOJSON_FUNC: ${{ toJSON(github) }}
          HASH_FUNC: ${{ hashFiles('.github/workflows/*.yml') }}
      - run: echo "-----------------------------------------------"
      - run: echo "条件分岐"
      - run: echo "-----------------------------------------------"
      - run: echo "triggered!!!!"
        if: ${{ contains(github.run_id, '1') }}
