name: Matrix
on: push

jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/steup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${RUNNER OS}" && node --version
