name: Parallel Job
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - id: first
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
  second:
    runs-on: ubuntu-latest
    needs:
      - first
    steps:
      - env:
          RESULT: ${{ needs.first.outputs.result }}
        run: echo "$RESULT"
  third:
    runs-on: ubuntu-latest
    needs:
      - second
    steps:
      - run: sleep 10 && echo 'First Job'
